// ============================================================================
// IMEM_equipe41 - instruction memory (combinational ROM)
// Firmware : app firmware
// Generated by scripts/gen_imem.py from firmware.txt (113 words)
// ============================================================================
module IMEM_equipe41 (
    input  wire [31:0] imem_addr,     // decoder-relative address
    input  wire        read_enable,
    output wire [31:0] imem_output
);
    wire [31:0] i_Address = imem_addr + 32'h0040_0000;
    reg  [31:0] r_Instruction;

    always @(*) begin
        case (i_Address)
            32'h00400000: r_Instruction = 32'hF0000437;
            32'h00400004: r_Instruction = 32'hF10004B7;
            32'h00400008: r_Instruction = 32'h0F000293;
            32'h0040000C: r_Instruction = 32'h00542423;
            32'h00400010: r_Instruction = 32'h0004A423;
            32'h00400014: r_Instruction = 32'h08000293;
            32'h00400018: r_Instruction = 32'h00542023;
            32'h0040001C: r_Instruction = 32'h00442283;
            32'h00400020: r_Instruction = 32'h0082F293;
            32'h00400024: r_Instruction = 32'hFE028CE3;
            32'h00400028: r_Instruction = 32'h00442903;
            32'h0040002C: r_Instruction = 32'h00042023;
            32'h00400030: r_Instruction = 32'h000109B7;
            32'h00400034: r_Instruction = 32'hFFF98993;
            32'h00400038: r_Instruction = 32'h00000A13;
            32'h0040003C: r_Instruction = 32'h00000B13;
            32'h00400040: r_Instruction = 32'h02000B93;
            32'h00400044: r_Instruction = 32'h124000EF;
            32'h00400048: r_Instruction = 32'h813509B3;
            32'h0040004C: r_Instruction = 32'h01651533;
            32'h00400050: r_Instruction = 32'h00AA6A33;
            32'h00400054: r_Instruction = 32'h008B0B13;
            32'h00400058: r_Instruction = 32'hFF7B16E3;
            32'h0040005C: r_Instruction = 32'h10C000EF;
            32'h00400060: r_Instruction = 32'h813509B3;
            32'h00400064: r_Instruction = 32'h00050A93;
            32'h00400068: r_Instruction = 32'h100000EF;
            32'h0040006C: r_Instruction = 32'h813509B3;
            32'h00400070: r_Instruction = 32'h00851513;
            32'h00400074: r_Instruction = 32'h00AAEAB3;
            32'h00400078: r_Instruction = 32'h0F0000EF;
            32'h0040007C: r_Instruction = 32'h00050B93;
            32'h00400080: r_Instruction = 32'h0E8000EF;
            32'h00400084: r_Instruction = 32'h00851513;
            32'h00400088: r_Instruction = 32'h00ABEBB3;
            32'h0040008C: r_Instruction = 32'h07799A63;
            32'h00400090: r_Instruction = 32'h3E800293;
            32'h00400094: r_Instruction = 32'h0752EA63;
            32'h00400098: r_Instruction = 32'h00397293;
            32'h0040009C: r_Instruction = 32'h00229293;
            32'h004000A0: r_Instruction = 32'h00000317;
            32'h004000A4: r_Instruction = 32'h10430313;
            32'h004000A8: r_Instruction = 32'h00530333;
            32'h004000AC: r_Instruction = 32'h00032383;
            32'h004000B0: r_Instruction = 32'h01032E03;
            32'h004000B4: r_Instruction = 32'h035E0E33;
            32'h004000B8: r_Instruction = 32'h01C385B3;
            32'h004000BC: r_Instruction = 32'h00497293;
            32'h004000C0: r_Instruction = 32'h00028E63;
            32'h004000C4: r_Instruction = 32'h000142B7;
            32'h004000C8: r_Instruction = 32'h02558333;
            32'h004000CC: r_Instruction = 32'h0255B3B3;
            32'h004000D0: r_Instruction = 32'h01035313;
            32'h004000D4: r_Instruction = 32'h01039393;
            32'h004000D8: r_Instruction = 32'h007365B3;
            32'h004000DC: r_Instruction = 32'h00BA6A63;
            32'h004000E0: r_Instruction = 32'h40BA0633;
            32'h004000E4: r_Instruction = 32'h00000513;
            32'h004000E8: r_Instruction = 32'h01000693;
            32'h004000EC: r_Instruction = 32'h02C0006F;
            32'h004000F0: r_Instruction = 32'h000A0613;
            32'h004000F4: r_Instruction = 32'h00100513;
            32'h004000F8: r_Instruction = 32'h02000693;
            32'h004000FC: r_Instruction = 32'h01C0006F;
            32'h00400100: r_Instruction = 32'h00200513;
            32'h00400104: r_Instruction = 32'h0080006F;
            32'h00400108: r_Instruction = 32'h00300513;
            32'h0040010C: r_Instruction = 32'h00000593;
            32'h00400110: r_Instruction = 32'h00000613;
            32'h00400114: r_Instruction = 32'h04000693;
            32'h00400118: r_Instruction = 32'h00D42023;
            32'h0040011C: r_Instruction = 32'h00058C13;
            32'h00400120: r_Instruction = 32'h00060C93;
            32'h00400124: r_Instruction = 32'h060000EF;
            32'h00400128: r_Instruction = 32'h0FFC7513;
            32'h0040012C: r_Instruction = 32'h058000EF;
            32'h00400130: r_Instruction = 32'h008C5513;
            32'h00400134: r_Instruction = 32'h0FF57513;
            32'h00400138: r_Instruction = 32'h04C000EF;
            32'h0040013C: r_Instruction = 32'h00000B13;
            32'h00400140: r_Instruction = 32'h02000B93;
            32'h00400144: r_Instruction = 32'h016CD533;
            32'h00400148: r_Instruction = 32'h0FF57513;
            32'h0040014C: r_Instruction = 32'h038000EF;
            32'h00400150: r_Instruction = 32'h008B0B13;
            32'h00400154: r_Instruction = 32'hFF7B18E3;
            32'h00400158: r_Instruction = 32'h00442283;
            32'h0040015C: r_Instruction = 32'h0082F293;
            32'h00400160: r_Instruction = 32'hFE029CE3;
            32'h00400164: r_Instruction = 32'hEB1FF06F;
            32'h00400168: r_Instruction = 32'h0084A283;
            32'h0040016C: r_Instruction = 32'h0022F293;
            32'h00400170: r_Instruction = 32'hFE028CE3;
            32'h00400174: r_Instruction = 32'h0004A423;
            32'h00400178: r_Instruction = 32'h0044A503;
            32'h0040017C: r_Instruction = 32'h0FF57513;
            32'h00400180: r_Instruction = 32'h00008067;
            32'h00400184: r_Instruction = 32'h0084A283;
            32'h00400188: r_Instruction = 32'h0042F293;
            32'h0040018C: r_Instruction = 32'hFE028CE3;
            32'h00400190: r_Instruction = 32'h00A4A023;
            32'h00400194: r_Instruction = 32'h0084A303;
            32'h00400198: r_Instruction = 32'h00136313;
            32'h0040019C: r_Instruction = 32'h0064A423;
            32'h004001A0: r_Instruction = 32'h00008067;
            32'h004001A4: r_Instruction = 32'h00000032;
            32'h004001A8: r_Instruction = 32'h00000064;
            32'h004001AC: r_Instruction = 32'h00000096;
            32'h004001B0: r_Instruction = 32'h0000001E;
            32'h004001B4: r_Instruction = 32'h0000000C;
            32'h004001B8: r_Instruction = 32'h00000018;
            32'h004001BC: r_Instruction = 32'h00000024;
            32'h004001C0: r_Instruction = 32'h00000006;

            default: r_Instruction = 32'h00000000;
        endcase
    end

    assign imem_output = read_enable ? r_Instruction : 32'h00000000;
endmodule
