// ============================================================================
// IMEM_equipe41 - instruction memory (combinational ROM)
// Firmware : official firmware
// Generated by scripts/gen_imem.py from firmware.txt (21 words)
// ============================================================================
module IMEM_equipe41 (
    input  wire [31:0] imem_addr,     // decoder-relative address
    input  wire        read_enable,
    output wire [31:0] imem_output
);
    wire [31:0] i_Address = imem_addr + 32'h0040_0000;
    reg  [31:0] r_Instruction;

    always @(*) begin
        case (i_Address)
            32'h00400000: r_Instruction = 32'hF0000437;
            32'h00400004: r_Instruction = 32'hF10004B7;
            32'h00400008: r_Instruction = 32'h00842283;
            32'h0040000C: r_Instruction = 32'h0F02E293;
            32'h00400010: r_Instruction = 32'h00542423;
            32'h00400014: r_Instruction = 32'h00442283;
            32'h00400018: r_Instruction = 32'h00429293;
            32'h0040001C: r_Instruction = 32'h00542023;
            32'h00400020: r_Instruction = 32'h0084A283;
            32'h00400024: r_Instruction = 32'h0022F293;
            32'h00400028: r_Instruction = 32'hFE028CE3;
            32'h0040002C: r_Instruction = 32'h0004A423;
            32'h00400030: r_Instruction = 32'h0044A303;
            32'h00400034: r_Instruction = 32'h0084A283;
            32'h00400038: r_Instruction = 32'h0042F293;
            32'h0040003C: r_Instruction = 32'hFE028CE3;
            32'h00400040: r_Instruction = 32'h0064A023;
            32'h00400044: r_Instruction = 32'h0084A303;
            32'h00400048: r_Instruction = 32'h00136313;
            32'h0040004C: r_Instruction = 32'h0064A423;
            32'h00400050: r_Instruction = 32'hFC5FF06F;

            default: r_Instruction = 32'h00000000;
        endcase
    end

    assign imem_output = read_enable ? r_Instruction : 32'h00000000;
endmodule
