// Generated by scripts/tollguard_model.py - do not edit
localparam integer N_VEC = 7;
task automatic load_vectors;
  begin
    // 0: Car, off-peak, RM50.00, 25 km  -> OK
    v_gpio_in[0]  = 8'h08;
    v_balance[0]  = 32'h00001388;
    v_km[0]       = 16'h0019;
    v_crc[0]      = 16'h8411;
    e_status[0]   = 8'h00;
    e_fare[0]     = 16'h015E;
    e_balance[0]  = 32'h0000122A;
    e_gpio_out[0] = 8'h10;
    // 1: Van, peak, RM100.00, 120 km  -> OK
    v_gpio_in[1]  = 8'h0D;
    v_balance[1]  = 32'h00002710;
    v_km[1]       = 16'h0078;
    v_crc[1]      = 16'hFA04;
    e_status[1]   = 8'h00;
    e_fare[1]     = 16'h0E8D;
    e_balance[1]  = 32'h00001883;
    e_gpio_out[1] = 8'h10;
    // 2: Lorry, low balance RM10.00, 80 km  -> LOW_BALANCE
    v_gpio_in[2]  = 8'h0A;
    v_balance[2]  = 32'h000003E8;
    v_km[2]       = 16'h0050;
    v_crc[2]      = 16'h6807;
    e_status[2]   = 8'h01;
    e_fare[2]     = 16'h0BD6;
    e_balance[2]  = 32'h000003E8;
    e_gpio_out[2] = 8'h20;
    // 3: Taxi, peak, RM1234.56, 300 km  -> OK
    v_gpio_in[3]  = 8'h0F;
    v_balance[3]  = 32'h0001E240;
    v_km[3]       = 16'h012C;
    v_crc[3]      = 16'h3E91;
    e_status[3]   = 8'h00;
    e_fare[3]     = 16'h08EF;
    e_balance[3]  = 32'h0001D951;
    e_gpio_out[3] = 8'h10;
    // 4: Car, exact balance RM1.70, 10 km  -> OK
    v_gpio_in[4]  = 8'h08;
    v_balance[4]  = 32'h000000AA;
    v_km[4]       = 16'h000A;
    v_crc[4]      = 16'h86F1;
    e_status[4]   = 8'h00;
    e_fare[4]     = 16'h00AA;
    e_balance[4]  = 32'h00000000;
    e_gpio_out[4] = 8'h10;
    // 5: Car, tampered frame (bad CRC)  -> CRC_ERROR
    v_gpio_in[5]  = 8'h08;
    v_balance[5]  = 32'h00001388;
    v_km[5]       = 16'h0019;
    v_crc[5]      = 16'hBEEF;
    e_status[5]   = 8'h02;
    e_fare[5]     = 16'h0000;
    e_balance[5]  = 32'h00000000;
    e_gpio_out[5] = 8'h40;
    // 6: Lorry, distance 1500 km out of range  -> OUT_OF_RANGE
    v_gpio_in[6]  = 8'h0A;
    v_balance[6]  = 32'h000DBBA0;
    v_km[6]       = 16'h05DC;
    v_crc[6]      = 16'h1490;
    e_status[6]   = 8'h03;
    e_fare[6]     = 16'h0000;
    e_balance[6]  = 32'h00000000;
    e_gpio_out[6] = 8'h40;
  end
endtask
