#!/usr/bin/env python3
"""
gen_imem.py - wrap an RVBL firmware.txt into the IMEM_equipe41 Verilog module.

firmware.txt lines (produced by the organisers' Makefile / bin2rom.py) look like
    32'h00400000: r_Instruction = 32'hF0000437;
They are pasted verbatim into the case statement, as required by the
RVBL-Firmware-Builder README. The module receives the decoder-relative address
(0x0 = 0x00400000) and rebuilds the absolute i_Address before the case.

usage: gen_imem.py firmware.txt "description" > IMEM_xxx.v
"""
import sys

def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gen_imem.py firmware.txt [description]")
    src = sys.argv[1]
    desc = sys.argv[2] if len(sys.argv) > 2 else src
    lines = [l.strip() for l in open(src) if l.strip()]
    for l in lines:
        if not (l.startswith("32'h") and "r_Instruction" in l):
            sys.exit(f"unexpected line in {src}: {l}")

    print(f"""// ============================================================================
// IMEM_equipe41 - instruction memory (combinational ROM)
// Firmware : {desc}
// Generated by scripts/gen_imem.py from {src.split('/')[-1]} ({len(lines)} words)
// ============================================================================
module IMEM_equipe41 (
    input  wire [31:0] imem_addr,     // decoder-relative address
    input  wire        read_enable,
    output wire [31:0] imem_output
);
    wire [31:0] i_Address = imem_addr + 32'h0040_0000;
    reg  [31:0] r_Instruction;

    always @(*) begin
        case (i_Address)""")
    for l in lines:
        print("            " + l)
    print("""
            default: r_Instruction = 32'h00000000;
        endcase
    end

    assign imem_output = read_enable ? r_Instruction : 32'h00000000;
endmodule""")

if __name__ == "__main__":
    main()
