#!/usr/bin/env python3
"""
tollguard_model.py - bit-exact reference model of the TollGuard firmware.

Generates, from one list of test scenarios:
  tb/app_vectors.vh     stimulus + expected results for tb_app_fw.v
  emu/emu_tests.sh      the matching ./emu command lines for the AWS stage

usage:  python3 scripts/tollguard_model.py            (writes both files)
        python3 scripts/tollguard_model.py --table    (prints a summary)
"""
import os, sys

BASE = [50, 100, 150, 30]      # sen, Class 1..4
RATE = [12, 24, 36, 6]         # sen / km
MAX_KM = 1000
PEAK_Q16 = 0x14000             # 1.25
ST_OK, ST_LOWBAL, ST_CRC, ST_RANGE = 0, 1, 2, 3
OUT_GATE, OUT_LOWBAL, OUT_FRAMEERR, OUT_READY = 0x10, 0x20, 0x40, 0x80
CLASS_NAME = ["Class 1 car", "Class 2 van", "Class 3 lorry", "Class 4 taxi"]
STATUS_NAME = ["OK", "LOW_BALANCE", "CRC_ERROR", "OUT_OF_RANGE"]


def crc16_ccitt_false(data, crc=0xFFFF):
    """CRC-16/CCITT-FALSE, identical to the Xicrc CRCB datapath."""
    for b in data:
        crc ^= b << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


def frame(balance, km):
    payload = balance.to_bytes(4, "little") + km.to_bytes(2, "little")
    return payload, crc16_ccitt_false(payload)


def toll(cls, peak, balance, km, crc_rx):
    """Returns (status, fare, new_balance, gpio_out) exactly as the firmware."""
    payload, crc = frame(balance, km)
    if crc != crc_rx:
        return ST_CRC, 0, 0, OUT_FRAMEERR
    if km > MAX_KM:
        return ST_RANGE, 0, 0, OUT_FRAMEERR
    fare = (BASE[cls] + RATE[cls] * km) & 0xFFFFFFFF
    if peak:
        fare = ((fare * PEAK_Q16) >> 16) & 0xFFFFFFFF
    if balance < fare:
        return ST_LOWBAL, fare, balance, OUT_LOWBAL
    return ST_OK, fare, balance - fare, OUT_GATE


# name, class(0-3), peak, balance(sen), km, crc override (None = correct)
SCENARIOS = [
    ("Car, off-peak, RM50.00, 25 km",          0, 0,   5000,   25, None),
    ("Van, peak, RM100.00, 120 km",            1, 1,  10000,  120, None),
    ("Lorry, low balance RM10.00, 80 km",      2, 0,   1000,   80, None),
    ("Taxi, peak, RM1234.56, 300 km",          3, 1, 123456,  300, None),
    ("Car, exact balance RM1.70, 10 km",       0, 0,    170,   10, None),
    ("Car, tampered frame (bad CRC)",          0, 0,   5000,   25, 0xBEEF),
    ("Lorry, distance 1500 km out of range",   2, 0, 900000, 1500, None),
]


def vectors():
    out = []
    for name, cls, peak, bal, km, crc_ovr in SCENARIOS:
        _, crc = frame(bal, km)
        crc_tx = crc if crc_ovr is None else crc_ovr
        st, fare, nbal, gpio = toll(cls, peak, bal, km, crc_tx)
        gpio_in = 0x08 | (peak << 2) | cls
        out.append(dict(name=name, cls=cls, peak=peak, bal=bal, km=km, crc=crc_tx,
                        gpio_in=gpio_in, st=st, fare=fare, nbal=nbal, gpio_out=gpio))
    return out


def write_vh(vs, path):
    with open(path, "w") as f:
        f.write("// Generated by scripts/tollguard_model.py - do not edit\n")
        f.write(f"localparam integer N_VEC = {len(vs)};\n")
        f.write("task automatic load_vectors;\n  begin\n")
        for i, v in enumerate(vs):
            f.write(f"    // {i}: {v['name']}  -> {STATUS_NAME[v['st']]}\n")
            f.write(f"    v_gpio_in[{i}]  = 8'h{v['gpio_in']:02X};\n")
            f.write(f"    v_balance[{i}]  = 32'h{v['bal']:08X};\n")
            f.write(f"    v_km[{i}]       = 16'h{v['km']:04X};\n")
            f.write(f"    v_crc[{i}]      = 16'h{v['crc']:04X};\n")
            f.write(f"    e_status[{i}]   = 8'h{v['st']:02X};\n")
            f.write(f"    e_fare[{i}]     = 16'h{v['fare']:04X};\n")
            f.write(f"    e_balance[{i}]  = 32'h{v['nbal']:08X};\n")
            f.write(f"    e_gpio_out[{i}] = 8'h{v['gpio_out']:02X};\n")
        f.write("  end\nendtask\n")


def write_emu(vs, path):
    with open(path, "w") as f:
        f.write("#!/usr/bin/env bash\n")
        f.write("# TollGuard - ./emu test commands (generated by scripts/tollguard_model.py)\n")
        f.write("# One ./emu call = one vehicle (the emulator resets the processor per call).\n")
        f.write("# Order follows the firmware protocol: trigger -> 8-byte frame -> 7-byte reply -> lamps.\n")
        f.write("#   -d 0xF0          P7-P4 observed (processor outputs), P3-P0 driven (inputs)\n")
        f.write("#   -o 0x80          READY lamp before the vehicle arrives\n")
        f.write("#   -i <P3..P0>      VEHICLE=1 | PEAK<<2 | CLASS\n")
        f.write("#   -t4 balance -t2 km -t2 crc16     tag frame (LSB first)\n")
        f.write("#   -r1 status -r2 fare -r4 balance  receipt (7 bytes <= 8-byte limit)\n")
        f.write("#   -o <lamps>       0x10 GATE / 0x20 LOW_BALANCE / 0x40 FRAME_ERROR\n\n")
        f.write('EMU=${EMU:-./emu}\n\n')
        for i, v in enumerate(vs):
            f.write(f"# [{i}] {v['name']}  -> {STATUS_NAME[v['st']]}"
                    f" (fare {v['fare']} sen, balance {v['nbal']} sen)\n")
            f.write(f"$EMU -d 0xF0 -o 0x80 -i 0x{v['gpio_in']:02X} "
                    f"-t4 0x{v['bal']:08X} -t2 0x{v['km']:04X} -t2 0x{v['crc']:04X} "
                    f"-r1 0x{v['st']:02X} -r2 0x{v['fare']:04X} -r4 0x{v['nbal']:08X} "
                    f"-o 0x{v['gpio_out']:02X}\n\n")
    os.chmod(path, 0o755)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    vs = vectors()
    if "--table" in sys.argv:
        print(f"{'#':<2} {'scenario':<40} {'in':>4} {'bal':>7} {'km':>5} {'crc':>6} "
              f"{'status':<13} {'fare':>6} {'new bal':>8} {'out':>4}")
        for i, v in enumerate(vs):
            print(f"{i:<2} {v['name']:<40} 0x{v['gpio_in']:02X} {v['bal']:>7} {v['km']:>5} "
                  f"0x{v['crc']:04X} {STATUS_NAME[v['st']]:<13} {v['fare']:>6} {v['nbal']:>8} "
                  f"0x{v['gpio_out']:02X}")
        return
    # sanity: the organisers' Stage 2 CRC test value
    assert crc16_ccitt_false(bytes([0x12,0x34,0x56,0x78,0x90,0xAB,0xCD,0xEF])) == 0x1E82
    write_vh(vs, os.path.join(root, "tb", "app_vectors.vh"))
    write_emu(vs, os.path.join(root, "emu", "emu_tests.sh"))
    print("wrote tb/app_vectors.vh and emu/emu_tests.sh")


if __name__ == "__main__":
    main()
