#!/usr/bin/env bash
# TollGuard - ./emu test commands (generated by scripts/tollguard_model.py)
# One ./emu call = one vehicle (the emulator resets the processor per call).
# Order follows the firmware protocol: trigger -> 8-byte frame -> 7-byte reply -> lamps.
#   -d 0xF0          P7-P4 observed (processor outputs), P3-P0 driven (inputs)
#   -o 0x80          READY lamp before the vehicle arrives
#   -i <P3..P0>      VEHICLE=1 | PEAK<<2 | CLASS
#   -t4 balance -t2 km -t2 crc16     tag frame (LSB first)
#   -r1 status -r2 fare -r4 balance  receipt (7 bytes <= 8-byte limit)
#   -o <lamps>       0x10 GATE / 0x20 LOW_BALANCE / 0x40 FRAME_ERROR

EMU=${EMU:-./emu}

# [0] Car, off-peak, RM50.00, 25 km  -> OK (fare 350 sen, balance 4650 sen)
$EMU -d 0xF0 -o 0x80 -i 0x08 -t4 0x00001388 -t2 0x0019 -t2 0x8411 -r1 0x00 -r2 0x015E -r4 0x0000122A -o 0x10

# [1] Van, peak, RM100.00, 120 km  -> OK (fare 3725 sen, balance 6275 sen)
$EMU -d 0xF0 -o 0x80 -i 0x0D -t4 0x00002710 -t2 0x0078 -t2 0xFA04 -r1 0x00 -r2 0x0E8D -r4 0x00001883 -o 0x10

# [2] Lorry, low balance RM10.00, 80 km  -> LOW_BALANCE (fare 3030 sen, balance 1000 sen)
$EMU -d 0xF0 -o 0x80 -i 0x0A -t4 0x000003E8 -t2 0x0050 -t2 0x6807 -r1 0x01 -r2 0x0BD6 -r4 0x000003E8 -o 0x20

# [3] Taxi, peak, RM1234.56, 300 km  -> OK (fare 2287 sen, balance 121169 sen)
$EMU -d 0xF0 -o 0x80 -i 0x0F -t4 0x0001E240 -t2 0x012C -t2 0x3E91 -r1 0x00 -r2 0x08EF -r4 0x0001D951 -o 0x10

# [4] Car, exact balance RM1.70, 10 km  -> OK (fare 170 sen, balance 0 sen)
$EMU -d 0xF0 -o 0x80 -i 0x08 -t4 0x000000AA -t2 0x000A -t2 0x86F1 -r1 0x00 -r2 0x00AA -r4 0x00000000 -o 0x10

# [5] Car, tampered frame (bad CRC)  -> CRC_ERROR (fare 0 sen, balance 0 sen)
$EMU -d 0xF0 -o 0x80 -i 0x08 -t4 0x00001388 -t2 0x0019 -t2 0xBEEF -r1 0x02 -r2 0x0000 -r4 0x00000000 -o 0x40

# [6] Lorry, distance 1500 km out of range  -> OUT_OF_RANGE (fare 0 sen, balance 0 sen)
$EMU -d 0xF0 -o 0x80 -i 0x0A -t4 0x000DBBA0 -t2 0x05DC -t2 0x1490 -r1 0x03 -r2 0x0000 -r4 0x00000000 -o 0x40

